[project]
name = "pytest-dockerctl"
version = "0.2.alpha"
description = "A pytest plugin managing containers using the docker-py API"
readme = "README.rst"
license = "MIT"
authors = [
  { name = "Tyler Goodlet", email = "tgoodlet@gmail.com" }
]
homepage = "https://github.com/tgoodlet/pytest-dockerctl"
keywords = ["pytest", "docker"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: MacOS :: MacOS X",
  "Topic :: Software Development :: Testing",
  "Programming Language :: Python :: 3"
]
requires-python = ">=3.6"
dependencies = [
  "docker",
  "pytest>=7.0.1",
  "pytest-trio>=0.7.0",
]

[project.entry-points."pytest11"]
dockerctl = "pytest_dockerctl"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
